---
run:
  dir: exp
sweep:
  dir: exp
  subdir: ${hydra.job.override_dirname}
job:
  chdir: True
launcher:
  submitit_folder: ${hydra.sweep.dir}/.submitit/%j
  timeout_min: 1
  cpus_per_task: 16
  gpus_per_node: 1
  partition: gpu
  constraint: a6000
  tasks_per_node: 1
  mem_gb: 128
  nodes: 1
  name: ${hydra.job.override_dirname}
  _target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
  comment: null
  exclude: gnodek1,gnodeg1,gnodeg3,gnodee4,gnodek2
  max_num_timeout: 0
  additional_parameters: {time: "3-00:00:00"}
  array_parallelism: 32
  setup: null
