name: PT_decoder

in_channels: 35
patch_embed_depth: 1
patch_embed_channels: 48
patch_embed_groups: 4
patch_embed_neighbours: 8
first_random_downsample: 2
enc_depths: [1, 1, 2, 1]
enc_channels: [64, 128, 256, 512]
enc_stride: [4, 2, 2, 2]
# grid_sizes: [0.12, 0.24, 0.48]
enc_groups: [8, 16, 32, 64]
enc_neighbours: [8, 8, 8, 8]
dec_depths: [1, 1, 1, 1]
dec_use_cross_attn: true
dec_channels: [48, 64, 128, 256]
dec_groups: [4, 8, 16, 32]
dec_neighbours: [8, 8, 8, 8]
attn_qkv_bias: false
pe_multiplier: true
pe_bias: true
attn_drop_rate: 0.0
drop_path_rate: 0.0
final_expansion: 2
norm_layer: ln
enable_checkpoint: false

