name: v3

in_channels: 35
enable_flash: True
output_dim: 96
enc_dim: 64
turn_off_bn:  False
stride: [1,2,2,2]
embedding_type: 'MLP'
enc_depths: [2, 2, 2, 6, 2]
enc_num_head: [2, 4, 8, 16, 32]
dec_depths: [2, 2, 2, 2]
dec_num_head: [4, 4, 8, 16]
dec_channels: 
enc_channels: 
pdnorm_bn: False
pdnorm_ln: False
pretrained_ckpt: 
