# name: v3_debug

# in_channels: 35
# enable_flash: True
# # output_dim: 64
# enc_dim: 64
# turn_off_bn: False
# stride: [1,2]
# embedding_type: 'MLP'
# enc_depths: [2, 6, 2]
# enc_num_head: [2, 4, 8]
# dec_depths: [2, 2]
# dec_num_head: [4, 8]
# dec_channels: [64, 128]
# enc_channels: [64, 128, 256]
# pdnorm_bn: False
# pdnorm_ln: False
# pretrained_ckpt: 

# delete_decoder_num: 0 ###### output_dim now depends on how many layers of decoder you want to delete
# all_layer_output: false


name: v3_debug

in_channels: 35
enable_flash: True
enc_dim: 64
# output_dim: 
turn_off_bn:  False
stride: [1,2,2]
embedding_type: 'MLP'
enc_depths: [2, 2, 6, 2]
enc_num_head: [2, 4, 8, 16]
dec_depths: [2, 2, 2]
dec_num_head: [4, 8, 16]
dec_channels: [64, 64, 128]
enc_channels: [64, 96, 128, 256]
pdnorm_bn: False
pdnorm_ln: False
pretrained_ckpt: 

delete_decoder_num: 1 ###### output_dim now depends on how many layers of decoder you want to delete
all_layer_output: true