defaults:
  - depth: unidepth
  - backbone: moge_encoder  # rgb_unidepth_encoder  moge_encoder
  - decoder_3d: v3_debug  # PT_decoder_debug v3_debug
  - unet3d: unet

name: gat_voxsplat
frame_ids: [0, -1, 1]
scales: [0]
gauss_novel_frames: [-1, 1, 2, -2, 3, -3, 4, -4]  #

# NOT USED
selective_padding: false
large_grad_threshold: 0.2
edge_padding_pixel: 14

use_decoder_3d: true
normalize_before_decoder_3d: true
grid_size: 0.01

version: v3

min_depth: 0.1
max_depth: 20

# gaussian parameters
gaussians_per_pixel: 1    ###### NOT used for overall padding, NEED TO REMOVE THIS CONFIG FINALLY
overall_padding: 1 # <- USE THIS CONFIG 

gaussian_rendering: true
randomise_bg_colour: true
max_sh_degree: 0
scaled_offset: false
one_gauss_decoder: false
predict_offset: true #
bg_colour: [0.5, 0.5, 0.5]
shift_rays_half_pixel: forward

predict_sh_offset: false
sh_offset_scale: 0.09

depth_type: depth_inc
depth_scale: 0.1 # 1.0
xyz_scale: 1e-02 # 1e-02
opacity_scale: 1e-3 # 1.0 1e-3
scale_scale: 1e-1 # 1e-1
sh_scale: 1.0

scale_lambda: 0.01
depth_bias: -0.1
xyz_bias: 0.0
opacity_bias: 0.1
scale_bias: 0.06

# point parameters
point_head_scale: 1e-2
point_head_bias: 0.0

# voxel parameters
voxel_size: 0.03
pc_range: [-5.12, -5.12, 0, 5.12, 5.12, 15.36]
coarse_voxel_size: 0.03
voxel_feat_dim: 32
dim_expand: 4

binary_predictor: false