defaults:
  - depth: unidepth
  - backbone: moge_encoder # rgb_unidepth_encoder  moge_encoder
  - decoder_3d: v3_debug  # PT_decoder_debug v3_debug

name: rgb_unidepth
frame_ids: [0, -1, 1]
scales: [0]
gauss_novel_frames: [-1, 1, 2] #

pre_downsample: false
voxel_size: 0.05

use_decoder_3d: true
normalize_before_decoder_3d: true

version: v3

min_depth: 0.1
max_depth: 20

# gaussian parameters
gaussians_per_pixel: 1
gaussian_rendering: true
randomise_bg_colour: true
max_sh_degree: 1
scaled_offset: false
one_gauss_decoder: false
predict_offset: false #
bg_colour: [0.5, 0.5, 0.5]
shift_rays_half_pixel: forward

predict_sh_offset: false
sh_offset_scale: 0.09

depth_type: depth_inc
depth_scale: 0.1 # 1.0
xyz_scale: 1e-02 # 1e-02
opacity_scale: 1e-3 # 1.0 1e-3
scale_scale: 1e-1 # 1e-1
sh0_scale: 1.5
sh_scale: 1.0

scale_lambda: 0.01
depth_bias: -0.1
xyz_bias: 0.0
opacity_bias: 0.01
scale_bias: 0.02
