name: pixelsplat
split: original
data_path: /mnt/datasets/realestate10k/re10k  #/data/datasets/re10k
depth_path: #/data/datasets/re10k
unpack_pcl_tar: false
preload_depths: false
ransac_on_the_fly: false
test_split_path: splits/re10k_mine_filtered/val2_files.txt

height: 224 #256 448 384 [462, 616]
width: 336 #384 672 608

znear: 0.01
zfar: 100.0
max_fov: 100.0

from_tar: false
copy_to_local: true
color_aug: false
skip_bad_shape: true
dilation: random
max_dilation: 15 #choose random target frame, maximum gap
pad_border_aug: 0
normalize: false
subset: -1  # use subset frames for small set overfitting

frame_sampling_method: random
scale_pose_by_depth: false
test_split: mine

#new
specific_files: [] 
random_selection: true

#probably used to exclude the outer edges of the image？
#In original evaluation.py file but not in original config, bug?
crop_border: true

#padding
#reshape
#