name: scannetpp
split: original
mode: iphone
data_path: /mnt/datasets/scannetpp_processed  #/data/datasets/re10k
depth_path: #/data/datasets/re10k
unpack_pcl_tar: false
preload_depths: false
ransac_on_the_fly: false
train_split_path: ['nvs_sem_train.txt', 'nvs_sem_val.txt']
test_split_path: ['mini_test.txt'] # 'nvs_test.txt'

height: 256 #256 448 384 [462, 616]
width: 384 #384 672 608

original_width: 1035.0 #1752 
original_height: 690.0 #1168

znear: 0.01
zfar: 100.0
max_fov: 100.0

from_tar: false
copy_to_local: true
color_aug: false
skip_bad_shape: true
dilation: random
max_dilation: 1 #choose random target frame, maximum gap
pad_border_aug: 0 # 32 0
normalize: false
subset: -1  # use subset frames for small set overfitting

frame_sampling_method: random
scale_pose_by_depth: false
test_split: mine

#new
specific_files: 
random_selection: false

#probably used to exclude the outer edges of the image？
#In original evaluation.py file but not in original config, bug?
crop_border: true

#padding
#reshape
#