defaults:
  - _self_
  - hydra: defaults
  - model: gaussian
  - dataset: pixelsplat
  - loss: [reconstruction, regularization]  ## originally only [reconstruction] loss

config:
  exp_name: "debug"
  file: "config.yaml"

data_loader:
  batch_size: 12
  num_workers: 16

train:
  logging: false 
  mixed_precision: 32-true #32-true, 16-mixed
  num_gpus: 1 #[1, 2, 3]
  load_weights_folder:
  ema:
    use: true
    update_every: 10
    update_after_step: 100
    beta: 0.9999

optimiser:
  learning_rate: 1e-4
  num_epochs: 1
  scheduler_lambda_step_size: 60000

run:
  resume_ckpt: null
  dirpath: null
  debug: false
  random_seed: 42
  git_hash: null
  log_frequency: 250
  save_frequency: 1000
  val_frequency: 5000
  num_keep_ckpts: 5

#new
#evaluation results save config
save_vis: true
video_mode: false
original_video: true
scene_ids: []
output_path: ./output

#ckpt path could be defined by user now
ckpt_path: ./exp/re10k_v2/checkpoints  #./exp/re10k_v2/checkpoints

add_mask: false #only used with depth input(scannetpp)


# #TO RUN TRAIN with pixelsplat dataset:
# python train.py

# set video_mode: false
# dataset.test_split_path: splits/re10k_mine_filtered/val_files.txt
# dataset.specific_files: [] 



#Things Modified:

##configs.model.gauss_novel_frames: [1, 2, 3] #originally [1, 2]

#File "/mnt/ziyuxiao/code/GaussianAnything/models/decoder/gauss_util.py", line 108, in render_predicted
# if cfg.model.renderer_w_pose: SET TRUE

# File "/mnt/ziyuxiao/code/GaussianAnything/models/model.py", line 211, in render_images
#   if cfg.train.use_gt_poses: SET TRUE

# cfg.dataset scale_pose_by_depth: false ??? originally true