dataset:
  is_train: true
  file_path: '/mnt/datasets/realestate10k/re10k/train/train1/'
  specific_files: ['000004'] 
  height: 256
  width: 384
  pad_border_aug: 32
  color_aug: false
  scales: [0]
  test_split_path: null  
  random_selection: False 
  subset: -1
  novel_frames: [1, 2, 3]
  dilation: random
  max_dilation: 15
  skip_bad_shape: false
  frame_sampling_method: random

eval: 
  output_path: './output'
  ckpt_path: './exp/re10k_v2/checkpoints'
  video_mode: true
  original_video: true
  scene_ids: []
train:
  output_path: './output'
  ckpt_path: #'./exp/re10k_v2/checkpoints'
  seed: 42
  num_gpus: 1
  mixed_precision: 32 #32-true, 16-mixed
  use_ema: true

  optimiser:
    learning_rate: 1e-4
    scheduler_lambda_step_size: 60000



#File "/mnt/ziyuxiao/code/GaussianAnything/models/decoder/gauss_util.py", line 108, in render_predicted
# if cfg.model.renderer_w_pose: SET TRUE

# File "/mnt/ziyuxiao/code/GaussianAnything/models/model.py", line 211, in render_images
#   if cfg.train.use_gt_poses: SET TRUE

# cfg.dataset scale_pose_by_depth: false ??? originally true
