eval: 
  is_train: false

  video_mode: false
  original_video: true
  save_vis: true
  dataset: scannetpp
  output_path: './output'
  ckpt_path: './exp/re10k_v2/checkpoints'
  scene_ids: []
train:
  is_train: true
  video_mode: false

  dataset: scannetpp
  output_path: './output'
  ckpt_path: #'./exp/re10k_v2/checkpoints'
  seed: 42
  num_gpus: 1
  mixed_precision: 32 #32-true, 16-mixed
  use_ema: true
  add_mask: false

  optimiser:
    learning_rate: 1e-4
    scheduler_lambda_step_size: 60000



#File "/mnt/ziyuxiao/code/GaussianAnything/models/decoder/gauss_util.py", line 108, in render_predicted
# if cfg.model.renderer_w_pose: SET TRUE

# File "/mnt/ziyuxiao/code/GaussianAnything/models/model.py", line 211, in render_images
#   if cfg.train.use_gt_poses: SET TRUE

# cfg.dataset scale_pose_by_depth: false ??? originally true
