dataset:
  mode: 'test'
  file_path: '/mnt/datasets/realestate10k/subset/test/000001.torch'
  height: 256
  width: 384
  pad_border_aug: 32
  do_color_aug: False
  scales: [0]
  test_split_path: null  
  random_selection: False 
eval: #use GAT_evaluate.py currently
  output_path: './output'
  ckpt_path: './exp/re10k_v2/checkpoints'
  video_mode: false
  scene_ids: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]


#File "/mnt/ziyuxiao/code/GaussianAnything/models/decoder/gauss_util.py", line 108, in render_predicted
# if cfg.model.renderer_w_pose: SET TRUE

# File "/mnt/ziyuxiao/code/GaussianAnything/models/model.py", line 211, in render_images
#   if cfg.train.use_gt_poses: SET TRUE

# cfg.dataset scale_pose_by_depth: false ??? originally true
