task_name: gat
defaults:
  - _self_
  - hydra: defaults
  - model: new_gat_model 
  - dataset: scannetpp # pixelsplat scannetpp arkitscenes
  - loss: [reconstruction, regularization]  # reconstruction, regularization

config:
  exp_name: "raycasting+soft" # binary_pred_mv_8gpu_fix
  file: "gat_config.yaml"

data_loader:
  batch_size: 1
  num_workers: 16

train:
  train_view_num: 3
  pretrain: false
  pretrain_warmup: -1
  logging: false 
  mixed_precision: 32-true # 32-true 16-mixed
  num_gpus: 1 #[1, 2, 3, 4, 5, 6]
  load_weights_folder: false
  load_pretrain: false
  freeze_pretrain: false
  ema:
    use: true
    update_every: 10
    update_after_step: 100
    beta: 0.9999

optimiser:
  learning_rate: 5e-5 # 1e-4 for total bs=32 (minibatch*gpu_num)
  num_epochs: 2
  scheduler_lambda_step_size: 500000
  weight_decay: 1e-4 # 1e-2 1e-4
  accumulation_steps: 1
  mode: cosine
  num_warmup_steps: 0
  warmup_ratio: 1.0
  max_training_steps: 240000
  min_lr_ratio: 0.1
  grad_clip: false
  max_norm: 1

run:
  resume_ckpt: null
  dirpath: null
  debug: false
  random_seed: 42
  git_hash: null
  log_frequency: 2500
  save_frequency: 5000
  val_frequency: 5000
  num_keep_ckpts: 3

#new
#evaluation results save config
save_vis: true
video_mode: false
original_video: false
scene_ids: []
output_path: ./output

#ckpt path could be defined by user now
ckpt_path: /mnt/ziyuxiao/code/GaussianAnything/output/raycasting+soft/gsm/ckpt #./exp/re10k_v2/checkpoints

add_mask: false #only used with depth input(scannetpp)


# #TO RUN TRAIN with pixelsplat dataset:
# python train.py

# set video_mode: false
# dataset.test_split_path: splits/re10k_mine_filtered/val_files.txt
# dataset.specific_files: [] 



#Things Modified:

##configs.model.gauss_novel_frames: [1, 2, 3] #originally [1, 2]

#File "/mnt/ziyuxiao/code/GaussianAnything/models/decoder/gauss_util.py", line 108, in render_predicted
# if cfg.model.renderer_w_pose: SET TRUE

# File "/mnt/ziyuxiao/code/GaussianAnything/models/model.py", line 211, in render_images
#   if cfg.train.use_gt_poses: SET TRUE

# cfg.dataset scale_pose_by_depth: false ??? originally true