file_path: '/mnt/ziyuxiao/code/scannetpp/data/scannetpp_demo'
specific_files: ['0a5c013435'] 
height: 256
width: 384
pad_border_aug: 32
color_aug: false
scales: [0]
test_split_path: null  
random_selection: true
subset: -1
novel_frames: [1, 2, 3]
dilation: random
max_dilation: 15
skip_bad_shape: false
frame_sampling_method: random

